### ISSUE TITLE
Generation of new key manually breaks dynamic changing of extension icon

### ISSUE THREAD

**Issue by cata85** [TeamHTP/hermes-chrome-extension#11] opened 2018-10-25 20:39 UTC
**Problem**
* When manually generating a new key the chrome extension icon changing breaks and stays grayed out.

**Acceptance Criteria**
* You can generate a new key without breaking the icon changing.

**Comment by tma02** [comment] 2018-10-26 17:57
Unable to reproduce. See #10

**Comment by tma02** [comment] 2018-10-28 01:16
Closing as @dominictassio and I were unable to reproduce.

**Closed by tma02** 2018-10-28 01:16 UTC
Labels: bug
